In [1]:
import numpy as np
horizon_ones = np.ones(shape=(1,4))
J = 0
m = 4
n = 2
db = 0
dw = np.zeros(shape=(2,1))
w = np.array([1,2]).astype(np.uint).reshape(1,2) # matran 1,2  (matran 1*n)
x = np.array([[3,4],[7,9],[4,2],[8,8]])  # matran 4,2 ( matran m*n)
y = np.array([1,1,0,1]).astype(np.uint)  # matran 1,4 (ma tran 1*m)
z = np.dot(w,x.T)  # transform x ve n*m sau do nhan 2 matran (1*n)*(n*m)
a = (1/(horizon_ones+np.exp(-z)))  # matran 1*m
dz = (y - a)  # ket qua cua matran 1*m - 1* m la ma tran 1*m
J = -(y*np.log(a) + (horizon_ones-y)*np.log(horizon_ones-a))
print(np.sum(J))
dw_result = np.sum((x*dz.repeat(2).reshape(4,2)).T,axis=1).reshape(2,1)    # dz nhan doi, reshape ve ma tran m*n, sau do nhan hadamard voi x (matran m*n) tra ve ma tran m*n
# lay matran m*n vua tim duoc tinh tong tren tung hang (aka tung m) -> tra ve matran 1*n -> trans form ve ma tran dw n*1 ban dau
db = np.sum(dz)/m
dw+=(dw_result/m)
print(dw)



8.000352107986169
[[-0.99965212]
 [-0.49981562]]


In [115]:
J = 0
m = 4
n = 2
db = 0
dw = np.zeros(shape=(2,1))
w = np.array([1,2]).astype(np.uint).reshape(1,2) # matran 1,2  (matran 1*n)
x = np.array([[3,4],[7,9],[4,2],[8,8]])  # matran 4,2 ( matran m*n)
y = np.array([1,1,0,1]).astype(np.uint)

for i in range(0,m):
    z = np.dot(w,x[i])
    a = (1/(1+np.exp(-z)))
    dz = - a + y[i]
    print(dz)
    for j in range(0,2):
        dw[j] += x[i][j]*dz[0]
    db += dz
db = db/m
dw /= m
print(dw)

[1.67014218e-05]
[1.38880019e-11]
[-0.99966465]
[3.77513576e-11]
[[-0.99965212]
 [-0.49981562]]


In [5]:
a =[1,2,3,4]
a = np.array(a)
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [5]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 0, keepdims = True) 
B.shape

(1, 3)